# Integer Behavior

In [28]:
import torch

In [4]:
2 ** 31

2147483648

In [5]:
torch.tensor(2 ** 31, dtype=torch.int64)

tensor(2147483648)

In [7]:
# torch.tensor(2 ** 31, dtype=torch.int32)    # number too large for 32 bits

In [10]:
x = torch.tensor(2 ** 31 - 1, dtype=torch.int32)
x

tensor(2147483647, dtype=torch.int32)

In [13]:
y = x + 1   # overflow
y

tensor(-2147483648, dtype=torch.int32)

In [15]:
y - 1   # underflow

tensor(2147483647, dtype=torch.int32)

# Float Behavior (Python is using float64 here)

In [16]:
from sys import float_info

In [17]:
float_info.max

1.7976931348623157e+308

In [18]:
float_info.min

2.2250738585072014e-308

In [19]:
big = float_info.max
small = -big

In [22]:
big + 1 == big

True

In [23]:
big * 2

inf

In [25]:
small * 3

-inf

In [26]:
big*2 + small*2

nan

In [29]:
big*2 + small*10

nan

In [31]:
float_info.dig

15

In [32]:
x = 1.23456781234567
y = 1.23456781234568
x == y

False

In [33]:
x = 1.2345678123456780
y = 1.2345678123456781
x == y

True

In [34]:
float_info.epsilon

2.220446049250313e-16

In [35]:
x = 1.0
x + float_info.epsilon    # the next number after 1.0

1.0000000000000002

In [36]:
x == x + float_info.epsilon

False

In [37]:
x == x + float_info.epsilon / 2

True

In [39]:
0.1 == 0.1 + float_info.epsilon / 2

False

# Matrices

In [61]:
torch.manual_seed(42)
A = torch.rand(10, 3, dtype=torch.float64)    # always get the same pseudorandom numbers
A

tensor([[0.0582, 0.0629, 0.1236],
        [0.0526, 0.5262, 0.4768],
        [0.9552, 0.9288, 0.0835],
        [0.1326, 0.1571, 0.3754],
        [0.8425, 0.8705, 0.3775],
        [0.6124, 0.0881, 0.7012],
        [0.6234, 0.4373, 0.0747],
        [0.6834, 0.3122, 0.3091],
        [0.0313, 0.0404, 0.9319],
        [0.1521, 0.2650, 0.1304]], dtype=torch.float64)

In [62]:
A.dtype

torch.float64

In [64]:
A.shape

torch.Size([10, 3])

In [65]:
A.device    # "cpu" means the main system memory (RAM)

device(type='cpu')

In [66]:
A.to(torch.float16)

tensor([[0.0582, 0.0629, 0.1236],
        [0.0526, 0.5264, 0.4768],
        [0.9551, 0.9287, 0.0836],
        [0.1327, 0.1571, 0.3755],
        [0.8423, 0.8706, 0.3774],
        [0.6123, 0.0881, 0.7012],
        [0.6235, 0.4373, 0.0747],
        [0.6836, 0.3123, 0.3091],
        [0.0313, 0.0404, 0.9321],
        [0.1521, 0.2651, 0.1305]], dtype=torch.float16)

In [69]:
torch.cuda.is_available()

False

In [70]:
if torch.cuda.is_available():
    A = A.to("cuda")

In [73]:
A.T    # transpose flips along the diaganol

tensor([[0.0582, 0.0526, 0.9552, 0.1326, 0.8425, 0.6124, 0.6234, 0.6834, 0.0313,
         0.1521],
        [0.0629, 0.5262, 0.9288, 0.1571, 0.8705, 0.0881, 0.4373, 0.3122, 0.0404,
         0.2650],
        [0.1236, 0.4768, 0.0835, 0.3754, 0.3775, 0.7012, 0.0747, 0.3091, 0.9319,
         0.1304]], dtype=torch.float64)

In [75]:
A.reshape(2,15)

tensor([[0.0582, 0.0629, 0.1236, 0.0526, 0.5262, 0.4768, 0.9552, 0.9288, 0.0835,
         0.1326, 0.1571, 0.3754, 0.8425, 0.8705, 0.3775],
        [0.6124, 0.0881, 0.7012, 0.6234, 0.4373, 0.0747, 0.6834, 0.3122, 0.3091,
         0.0313, 0.0404, 0.9319, 0.1521, 0.2650, 0.1304]], dtype=torch.float64)

In [76]:
A.reshape(30)

tensor([0.0582, 0.0629, 0.1236, 0.0526, 0.5262, 0.4768, 0.9552, 0.9288, 0.0835,
        0.1326, 0.1571, 0.3754, 0.8425, 0.8705, 0.3775, 0.6124, 0.0881, 0.7012,
        0.6234, 0.4373, 0.0747, 0.6834, 0.3122, 0.3091, 0.0313, 0.0404, 0.9319,
        0.1521, 0.2650, 0.1304], dtype=torch.float64)

In [79]:
A.nelement()

30

In [80]:
A.element_size()

8

In [82]:
A.nelement() * A.element_size()    # "about" how much memory used

240

In [84]:
# extra memory that we'll ignore:
import sys
sys.getsizeof(A)

80

# Calculations

In [85]:
X = torch.rand(5,3)
X

tensor([[0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958],
        [0.9147, 0.2036, 0.2018],
        [0.2018, 0.9497, 0.6666],
        [0.9811, 0.0874, 0.0041]])

In [86]:
X + 100

tensor([[100.5315, 100.1587, 100.6542],
        [100.3278, 100.6532, 100.3958],
        [100.9147, 100.2037, 100.2018],
        [100.2018, 100.9497, 100.6666],
        [100.9811, 100.0874, 100.0041]])

In [92]:
torch.sigmoid(torch.tensor(0))

tensor(0.5000)

In [94]:
torch.sigmoid(torch.arange(-5,6,1))

tensor([0.0067, 0.0180, 0.0474, 0.1192, 0.2689, 0.5000, 0.7311, 0.8808, 0.9526,
        0.9820, 0.9933])

In [98]:
x = torch.rand(5,3)
y = torch.rand(3,7)
z = torch.rand(7,2)

# rule 1: 2nd dim of 1st matrix must equal 1st dim of 2nd matrix (for every pair)
# rule 2: final rows=rows of first matrix; final cols=cols of last matrix
# matrix multiply
x @ y @ z

tensor([[0.8167, 1.2725],
        [2.0313, 2.2718],
        [1.2208, 1.8890],
        [1.4489, 1.9806],
        [0.9234, 1.4883]])