In [1]:
import torch

In [3]:
2 ** 31

2147483648

In [4]:
torch.tensor(2**31, dtype=torch.int64)

tensor(2147483648)

In [7]:
x = torch.tensor(2**31 - 1, dtype=torch.int32)
x

tensor(2147483647, dtype=torch.int32)

In [11]:
y = x + 1 # overflow: number gets too big -- wraps around to a negative number
y

tensor(-2147483648, dtype=torch.int32)

In [13]:
y - 1  # underflow

tensor(2147483647, dtype=torch.int32)

In [16]:
from sys import float_info

In [17]:
dir(float_info)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__match_args__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'dig',
 'epsilon',
 'index',
 'mant_dig',
 'max',
 'max_10_exp',
 'max_exp',
 'min',
 'min_10_exp',
 'min_exp',
 'n_fields',
 'n_sequence_fields',
 'n_unnamed_fields',
 'radix',
 'rounds']

In [18]:
float_info.min, float_info.max

(2.2250738585072014e-308, 1.7976931348623157e+308)

In [20]:
big = float_info.max
big

1.7976931348623157e+308

In [21]:
small = -big
small

-1.7976931348623157e+308

In [23]:
big == big + 1

True

In [24]:
big * 2

inf

In [26]:
small * 3

-inf

In [27]:
big * 2 + small * 2

nan

In [28]:
big * 2 + small * 10

nan

In [30]:
big * 2 / 2

inf

In [33]:
big, big * 0.9

(1.7976931348623157e+308, 1.6179238213760842e+308)

In [36]:
float_info.dig # how many digits can we do faithfully

15

In [38]:
x = 1.23456781234567
y = 1.23456781234568
x == y

False

In [46]:
x = 1.2345678123456782
y = 1.2345678123456783
x == y   # not precise enough!

True

In [48]:
1.0 + float_info.epsilon   # the next valid float after 1

1.0000000000000002

In [49]:
x = 1.0
y = x + float_info.epsilon
x == y

False

In [50]:
x = 1.0
y = x + float_info.epsilon / 2
x == y

True

In [51]:
x = 0.1
y = x + float_info.epsilon / 2
x == y

False

# Matrices, Doing Ops on Them

In [79]:
torch.manual_seed(42)
A = torch.rand(10, 3)   # pseudorandom numbers
A

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]])

In [80]:
A.dtype

torch.float32

In [81]:
A.shape

torch.Size([10, 3])

In [82]:
A.device    # "cpu" means regular system memory (RAM)

device(type='cpu')

In [83]:
A.nelement() * A.element_size()   # "about" how many bytes are used

120

In [85]:
import sys
sys.getsizeof(A)   # extra bytes that Python uses
                   # (we will NOT count these because it matter when matrices are large)

80

In [87]:
A.to(torch.float64)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]], dtype=torch.float64)

In [91]:
if torch.cuda.is_available():
    A = A.to("cuda")

In [93]:
A.T # transpose: flip along the diaganol

tensor([[0.8823, 0.9593, 0.2566, 0.1332, 0.8694, 0.4294, 0.2666, 0.4414, 0.1053,
         0.1994],
        [0.9150, 0.3904, 0.7936, 0.9346, 0.5677, 0.8854, 0.6274, 0.2969, 0.2695,
         0.5472],
        [0.3829, 0.6009, 0.9408, 0.5936, 0.7411, 0.5739, 0.2696, 0.8317, 0.3588,
         0.0062]])

In [97]:
A.reshape(30)

tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
        0.1332, 0.9346, 0.5936, 0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739,
        0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588,
        0.1994, 0.5472, 0.0062])